export class ConstantException {
  static ENTITY_NOT_FOUND: string = 'Entity not found'
  static RESOURCE_NOT_FOUND: string = 'Resource not found'
  static VALID_SORT: string = 'No valid sortable fields were defined'
  static USER_NOT_FOUND: string = 'User not found'
  static DATA_INTEGRITY_VIOLATION: string = 'Data integrity violation'
  static INVALID_USER: string = 'Invalid user'
  static ACCESS_DENIED: string = 'Access denied'
  static FORBIDDEN: string = 'Forbidden execption'
  static NOT_FOUND: string = '.Resource not found'
  static BAD_REQUEST: string = 'Database exception'
  static UNPROCESSABLE_ENTITY: string = 'Validation exception'
  static UNAUTHORIZED: string = 'Unauthorized'
  static CREDENTIALS_NOT_MATCH: string = 'User credentials do not match'
  static DUPLICATE: string = 'This field duplicate'
  static FIELD_REQUIRED: string = 'This field is mandatory'
  static EMAIL_REQUIRED: string = 'Please enter a valid email address'
  static EMAIL_NOT_FOUND: string = 'Email not found'
  static EMAIL_EXIST: string = 'Email address alredy used'
  static PRICE_POSITIVO_REQUIRED: string = 'Price must be a positive value'
  static CONFICT_EMAIL: string = 'User with same e-mail already exists'
  static CONFICT: string = 'Conflict'
  static DATA_PRESENT_REQUIRED: string =
    'The product date cannot be in the future'
  static OLD_PASSWORD_NOT_MATH: string = 'Old password does not math'
  static OLD_PASSWORD_AND_NEW_PASSWORD_REQUERID: string =
    'Old password and new password is required'
  static PASSWORD_NOT_MATCH: string = 'Password do not match!'
}
